# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript


trigger:
- none

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
   :: Create an exclusions file for PoliCheck
   :: Set Policheck to reference this file at PoliCheck->Advanced->User Exclusions File
   
   set exclusionFile=   %BUILD_SOURCESDIRECTORY%\UserExclusion.xml
   
   echo ^<PoliCheckExclusions^> >> %exclusionFile%
   echo ^<Exclusion Type="FolderPathStart"^>.GIT^</Exclusion^> >> %exclusionFile%
   echo ^</PoliCheckExclusions^> >> %exclusionFile%
   
   ::<PoliCheckExclusions>
   ::
   ::  <!-- All strings must be UPPER CASE -->
   ::
   ::  <!--Each of these exclusions is a folder name -if \[name]\exists in the file path, it will be skipped -->
   ::  <!--<Exclusion Type="FolderPathFull">ABC|XYZ</Exclusion>-->
   ::
   ::  <!--Each of these exclusions is a folder name -if any folder or file starts with "\[name]", it will be skipped -->
   ::  <!--<Exclusion Type="FolderPathStart">ABC|XYZ</Exclusion>-->
   ::
   ::  <!--Each of these file types will be completely skipped for the entire scan -->
   ::  <!--<Exclusion Type="FileType">.ABC|.XYZ</Exclusion>-->
   ::
   ::  <!--The specified file names will be skipped during the scan regardless which folder they are in -->
   ::  <!--<Exclusion Type="FileName">ABC.TXT|XYZ.CS</Exclusion>-->
   ::
   ::</PoliCheckExclusions>
  displayName: 'Set Policheck exclusions'

- task: CredScan@2
  inputs:
    toolMajorVersion: 'V2'

- task: ESLint@1
  inputs:
    Configuration: 'recommended'
    TargetType: 'eslint'
    ErrorLevel: 'warn'

- task: PoliCheck@1
  displayName: 'Run PoliCheck'
  inputs:
    targetType: F
    SOMEnabled: true
    optionsFC: 1
    optionsUEPATH: '$(Build.SourcesDirectory)\UserExclusion.xml'

- task: Semmle@0
  env: 
    SYSTEM_ACCESSTOKEN: $(PATToken)
  inputs:
    sourceCodeDirectory: '$(Build.SourcesDirectory)'
    language: 'tsandjs'
    includeNodeModules: true
    querySuite: 'Recommended'
    timeout: '1800'
    ram: '16384'
    addProjectDirToScanningExclusionList: true

- task: ComponentGovernanceComponentDetection@0
  inputs:
    scanType: 'Register'
    verbosity: 'Verbose'
    alertWarningLevel: 'High'

- task: PublishSecurityAnalysisLogs@2
  inputs:
    ArtifactName: 'CodeAnalysisLogs'
    ArtifactType: 'Container'
    AllTools: true
    ToolLogsNotFoundAction: 'Standard'
